python l2_regularization.py --gm_op NGD --na_op CG
python l2_regularization.py --gm_op NGD --na_op CG,PTT
python l2_regularization.py --gm_op NGD --na_op RAD
python l2_regularization.py --gm_op NGD --na_op RAD,PTT
python l2_regularization.py --gm_op NGD --na_op RAD,RGT
python l2_regularization.py --gm_op NGD --na_op PTT,RAD,RGT
python l2_regularization.py --gm_op NGD --na_op FD
python l2_regularization.py --gm_op NGD --na_op FD,PTT
python l2_regularization.py --gm_op NGD --na_op NS
python l2_regularization.py --gm_op NGD --na_op NS,PTT
python l2_regularization.py --gm_op NGD --na_op IGA
python l2_regularization.py --gm_op NGD --na_op IGA,PTT
python l2_regularization.py --gm_op DI,NGD --na_op CG
python l2_regularization.py --gm_op DI,NGD --na_op CG,PTT
python l2_regularization.py --gm_op DI,NGD --na_op RAD
python l2_regularization.py --gm_op DI,NGD --na_op RAD,PTT
python l2_regularization.py --gm_op DI,NGD --na_op RAD,RGT
python l2_regularization.py --gm_op DI,NGD --na_op PTT,RAD,RGT
python l2_regularization.py --gm_op DI,NGD --na_op FD
python l2_regularization.py --gm_op DI,NGD --na_op FD,PTT
python l2_regularization.py --gm_op DI,NGD --na_op NS
python l2_regularization.py --gm_op DI,NGD --na_op NS,PTT
python l2_regularization.py --gm_op DI,NGD --na_op IGA
python l2_regularization.py --gm_op DI,NGD --na_op IGA,PTT
python l2_regularization.py --gm_op GDA,NGD --na_op CG
python l2_regularization.py --gm_op GDA,NGD --na_op CG,PTT
python l2_regularization.py --gm_op GDA,NGD --na_op RAD
python l2_regularization.py --gm_op GDA,NGD --na_op RAD,PTT
python l2_regularization.py --gm_op GDA,NGD --na_op RAD,RGT
python l2_regularization.py --gm_op GDA,NGD --na_op PTT,RAD,RGT
python l2_regularization.py --gm_op GDA,NGD --na_op FD
python l2_regularization.py --gm_op GDA,NGD --na_op FD,PTT
python l2_regularization.py --gm_op GDA,NGD --na_op NS
python l2_regularization.py --gm_op GDA,NGD --na_op NS,PTT
python l2_regularization.py --gm_op GDA,NGD --na_op IGA
python l2_regularization.py --gm_op GDA,NGD --na_op IGA,PTT
python l2_regularization.py --gm_op GDA,NGD,DI --na_op CG
python l2_regularization.py --gm_op GDA,NGD,DI --na_op CG,PTT
python l2_regularization.py --gm_op GDA,NGD,DI --na_op RAD
python l2_regularization.py --gm_op GDA,NGD,DI --na_op RAD,PTT
python l2_regularization.py --gm_op GDA,NGD,DI --na_op RAD,RGT
python l2_regularization.py --gm_op GDA,NGD,DI --na_op PTT,RAD,RGT
python l2_regularization.py --gm_op GDA,NGD,DI --na_op FD
python l2_regularization.py --gm_op GDA,NGD,DI --na_op FD,PTT
python l2_regularization.py --gm_op GDA,NGD,DI --na_op NS
python l2_regularization.py --gm_op GDA,NGD,DI --na_op NS,PTT
python l2_regularization.py --gm_op GDA,NGD,DI --na_op IGA
python l2_regularization.py --gm_op GDA,NGD,DI --na_op IGA,PTT
python l2_regularization.py --gm_op DI,NGD,GDA --na_op CG
python l2_regularization.py --gm_op DI,NGD,GDA --na_op CG,PTT
python l2_regularization.py --gm_op DI,NGD,GDA --na_op RAD
python l2_regularization.py --gm_op DI,NGD,GDA --na_op RAD,PTT
python l2_regularization.py --gm_op DI,NGD,GDA --na_op RAD,RGT
python l2_regularization.py --gm_op DI,NGD,GDA --na_op PTT,RAD,RGT
python l2_regularization.py --gm_op DI,NGD,GDA --na_op FD
python l2_regularization.py --gm_op DI,NGD,GDA --na_op FD,PTT
python l2_regularization.py --gm_op DI,NGD,GDA --na_op NS
python l2_regularization.py --gm_op DI,NGD,GDA --na_op NS,PTT
python l2_regularization.py --gm_op DI,NGD,GDA --na_op IGA
python l2_regularization.py --gm_op DI,NGD,GDA --na_op IGA,PTT
python l2_regularization.py --gm_op DM --na_op RAD
python l2_regularization.py --gm_op DM --na_op CG
python l2_regularization.py --gm_op DM,GDA --na_op RAD
python l2_regularization.py --gm_op DM,GDA --na_op CG
python l2_regularization.py --fo_op VSO
python l2_regularization.py --fo_op VFO
python l2_regularization.py --fo_op MESO
python l2_regularization.py --fo_op PGDO
