codecov:
 token: 9dd0aac2-35f6-4de6-a371-3304886540c5

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0.2
        base: auto 
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch:
      default:
        # basic
        target: auto
        threshold: 0.2
        base: auto 
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null

ignore:
    # ignore the base classes which will be automatically inherited.
  - "boat/utils/op_utils.py"
