name: tests
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@main
    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python }}
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Generate coverage report
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pytest --cov=boat --cov-report=xml data_hyper_cleaning
        pytest --cov=boat --cov-report=xml meta_learning
    - name: Statistics
      if: success()
      run: |
        coverage report
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml,!./cache
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
