name: tests
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@main
      with:
        python-version: '3.8'
    - name: Install requirements
      run: pip install -r requirements.txt

    - name: List files in BOAT/data_hyper_cleaning
      run: ls -al BOAT/data_hyper_cleaning

    - name: List the contents of the repository
      run: ls -al /home/runner/work/BOAT/BOAT

    - name: List files in BOAT/meta_learning
      run: ls -al BOAT/meta_learning

    - name: Generate coverage report
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pytest --cov=boat --cov-report=xml BOAT/data_hyper_cleaning/test_data_hyper_cleaning.py
        pytest --cov=boat --cov-report=xml BOAT/meta_learning/test_meta_cleaning.py
    - name: Statistics
      if: success()
      run: |
        coverage report
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml,!./cache
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
